package org.ck.pduLibrary.types;

public enum ProtocolIdentifier
{

	IMPLICIT(0x00),
	TELEX(0x01),
	GROUP_3_TELEFAX(0x02),
	GROUP_4_TELEFAX(0x03),
	VOICE_TELEPHONE(0x04),
	ERMES(0x05), /* European Radio Messaging System */
	NATIONAL_PAGING_SYSTEM(0x06),
	VIDEOTEX(0x07), /* T.100 [20] /T.101 [21] */
	TELETEX_UNSPECIFIED(0x08),
	TELETEX_PSPDN(0x09),
	TELETEX_CSPDN(0x0A),
	TELETEX_ANALOG_PSTN(0x0B),
	TELETEX_DIGITAL_ISDN(0x0C),
	UCI(0x0D), /* Universal Computer Interface, ETSI DE/PS 3 01-3) */
	/* reserved */
	MESSAGE_HANDLING_FACILITY(0x10),
	X400(0x11),
	INTERNET_ELECTRONIC_MAIL(0x12),
	/* reserved */
	SC_RESERVED1(0x18),
	SC_RESERVED2(0x19),
	SC_RESERVED3(0x1A),
	SC_RESERVED4(0x1B),
	SC_RESERVED5(0x1C),
	SC_RESERVED6(0x1D),
	SC_RESERVED7(0x1E),
	GSM_UMTS_MOBILE_STATION(0x1F),
	
	SHORT_MESSAGE_TYPE_0(0x40),
	REPLACE_SHORT_MESSAGE_TYPE_1(0x41),
	REPLACE_SHORT_MESSAGE_TYPE_2(0x42),
	REPLACE_SHORT_MESSAGE_TYPE_3(0x43),
	REPLACE_SHORT_MESSAGE_TYPE_4(0x44),
	REPLACE_SHORT_MESSAGE_TYPE_5(0x45),
	REPLACE_SHORT_MESSAGE_TYPE_6(0x46),
	REPLACE_SHORT_MESSAGE_TYPE_7(0x47),
	DEVICE_TRIGGERING_SHORT_MESSAGE(0x48),
	/* reserved */
	ENHANCED_MESSAGE_SERVICE(0x5D), /* obsolete */
	RETURN_CALL_MESSAGE(0x5F),
	/* reserved */
	ANSI_136_R_DATA(0x7C),
	ME_DATA_DOWNLOAD(0x7D),
	ME_DATA_DE_PERSONALIZATION_SHORT_MESSAGE(0x7E),
	USIM_DATA_DOWNLOAD(0x7F);

	
	private Integer value;
			
	ProtocolIdentifier(Integer value)
	{
		this.value = value;
	}
	
	public Integer getValue()
	{
		return value;
	}
	
}
